### ISSUE TITLE
Question about the normal calculation method

### ISSUE THREAD

**Issue by ulassbin** [Enderdead/PCL-Normal-Estimation-2d#3]
Hi, I have been using this repo for a while now with the fork I have created. This was very useful to me and I have used this in my ms thesis. I have understood how you computed the normals by finding the eigenvectors of the alpha matrix but, I would like to refer to this method by its 'scientific name' if there is any. I am planning to cite this repo and the method that you are using. I would like to know if there is any 'scientific term' for calculating normals this way. 

Thanks in advance,
Ulaş

**Comment by Enderdead** [comment]
Hello, 
This method is based on the plane estimation around the target point of your cloud point. You want that your normal estimation minimizes the error between the induced plan and the neighbourhood of the target point. You can find in this paper  the academic reference of this : https://web.cse.ohio-state.edu/~dey.8/paper/normal/normal.pdf (the first method cited [HDD∗92] )

Keep in mind that this repo is only a hack of the original method developed in the official PCL library, where the normal is estimated with the PCA algorithm which approximates the optimization problem.

**Comment by ulassbin** [comment]
Thanks
